import './style';
import Select from 'antd/lib/select';
export { Select };
import Input from 'antd/lib/input';
export { Input };
import Form from 'antd/lib/form';
export { Form };
import Button from 'antd/lib/button';
export { Button };
import Icon from 'antd/lib/icon';
export { Icon };
